# Generated by Django 3.0.1 on 2020-01-01 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guitar_name', models.CharField(max_length=50)),
                ('guitar_price', models.IntegerField()),
                ('guitar_image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Individualguitar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guitar_type', models.CharField(max_length=50)),
                ('cut', models.CharField(max_length=50)),
                ('truss', models.CharField(max_length=5)),
                ('top', models.CharField(max_length=50)),
                ('sideback', models.CharField(max_length=50)),
                ('feature_1', models.CharField(max_length=50)),
                ('feature_2', models.CharField(max_length=50)),
                ('feature_3', models.CharField(max_length=50)),
                ('feature_4', models.CharField(max_length=50)),
                ('pickup', models.CharField(max_length=50)),
                ('iguitar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capo.Guitar')),
            ],
        ),
    ]
