# Generated by Django 3.0.1 on 2020-01-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capo', '0003_auto_20200102_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='cut',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guitar',
            name='feature_1',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guitar',
            name='feature_2',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guitar',
            name='feature_3',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guitar',
            name='feature_4',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guitar',
            name='guitar_type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guitar',
            name='pickup',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guitar',
            name='sideback',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guitar',
            name='top',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guitar',
            name='truss',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Individualguitar',
        ),
    ]
