# Generated by Django 3.0.1 on 2020-01-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capo', '0005_auto_20200104_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparel',
            name='feature_1',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apparel',
            name='feature_2',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apparel',
            name='feature_3',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Individualapparel',
        ),
    ]
